-- V1: initial schema for fintrack
-- Matches entities: User (users), Account (accounts), Transaction (transactions)

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE accounts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount       NUMERIC(19, 2) NOT NULL,
    currency     VARCHAR(3)     NOT NULL,
    account_name VARCHAR(255)   NOT NULL,
    user_id      BIGINT         NOT NULL,
    CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_account_owner ON accounts (user_id);

CREATE TABLE transactions (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_account_id      BIGINT,
    destination_account_id BIGINT,
    type                   VARCHAR(255)   NOT NULL,
    amount                 NUMERIC(19, 2) NOT NULL,
    currency               VARCHAR(3)     NOT NULL,
    name                   VARCHAR(255)   NOT NULL,
    category               VARCHAR(255)   NOT NULL,
    occurred_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_transactions_source      FOREIGN KEY (source_account_id)      REFERENCES accounts (id),
    CONSTRAINT fk_transactions_destination FOREIGN KEY (destination_account_id) REFERENCES accounts (id),
    CONSTRAINT ck_transactions_type   CHECK (type IN ('INCOME', 'EXPENSE', 'TRANSFER')),
    CONSTRAINT ck_transactions_amount CHECK (amount > 0),
    -- Mirrors the factory methods: which account columns are set depends on the type
    CONSTRAINT ck_transactions_accounts CHECK (
        (type = 'EXPENSE'  AND source_account_id IS NOT NULL AND destination_account_id IS NULL) OR
        (type = 'INCOME'   AND source_account_id IS NULL     AND destination_account_id IS NOT NULL) OR
        (type = 'TRANSFER' AND source_account_id IS NOT NULL AND destination_account_id IS NOT NULL
                           AND source_account_id <> destination_account_id)
    )
);

CREATE INDEX idx_transactions_source      ON transactions (source_account_id);
CREATE INDEX idx_transactions_destination ON transactions (destination_account_id);