package com.yokonev.fintrack.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.when;

import java.util.NoSuchElementException;
import java.util.Optional;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.test.util.ReflectionTestUtils;

import com.yokonev.fintrack.dto.UserResponse;
import com.yokonev.fintrack.entity.AppUser;
import com.yokonev.fintrack.repository.UserRepository;

@ExtendWith(MockitoExtension.class)
class UserServiceImplTest {

    private static final Long USER_ID = 42L;
    private static final String USERNAME = "alice";
    private static final String EMAIL = "alice@example.com";
    private static final String PASSWORD_HASH = "$2a$10$hashedpassword";

    @Mock
    private UserRepository userRepo;

    @InjectMocks
    private UserServiceImpl userService;

    private AppUser user;

    @BeforeEach
    void setUp() {
        user = new AppUser(USERNAME, EMAIL, PASSWORD_HASH);
        ReflectionTestUtils.setField(user, "id", USER_ID); // Normally generated by JPA
    }

    @Nested
    class LoadUserByUsernameTest {

        @Test
        @DisplayName("Returns UserDetails with stored credentials when user exists")
        void returnsUserDetailsWithStoredCredentialsTest() {
            when(userRepo.findByEmail(EMAIL)).thenReturn(Optional.of(user));

            UserDetails details = userService.loadUserByUsername(EMAIL);

            assertEquals(USERNAME, details.getUsername());
            assertEquals(PASSWORD_HASH, details.getPassword());
        }

        @Test
        @DisplayName("Throws UsernameNotFoundException when user does not exist")
        void userNotFoundThrowsExceptionTest() {
            when(userRepo.findByEmail(EMAIL)).thenReturn(Optional.empty());

            assertThrows(UsernameNotFoundException.class, 
                () -> userService.loadUserByUsername(EMAIL)
            );
        }

        @Test
        @DisplayName("Grants no user authorities when user exists")
        void grantsNoAuthoritiesTest() {
            when(userRepo.findByEmail(EMAIL)).thenReturn(Optional.of(user));

            UserDetails details = userService.loadUserByUsername(EMAIL);

            assertTrue(details.getAuthorities().isEmpty());
        }
    }

    @Nested
    class GetUserById {

        @Test
        @DisplayName("A user fetched from a repo by id maps user correctly to a response")
        void mapsUserToResponseTest() {
            when(userRepo.findById(USER_ID)).thenReturn(Optional.of(user));

            UserResponse response = userService.getUserById(USER_ID);

            assertEquals(new UserResponse(USER_ID, USERNAME, EMAIL), response);
        }

        @Test
        @DisplayName("Throws NoSuchElementException when user does not exist")
        void throwsNoSuchElementWithIdWhenUserDoesNotExistTest() {
            when(userRepo.findById(99L)).thenReturn(Optional.empty());

            assertThrows(NoSuchElementException.class,
                () -> userService.getUserById(99L)
            );
        }
    }

    @Nested
    class GetUserByEmail {

        @Test
        @DisplayName("A user fetched from a repo by username maps user correctly to a response")
        void mapsUserToResponseTest() {
            when(userRepo.findByEmail(EMAIL)).thenReturn(Optional.of(user));

            UserResponse response = userService.getUserByEmail(EMAIL);

            assertEquals(new UserResponse(USER_ID, USERNAME, EMAIL), response);
        }

        @Test
        @DisplayName("Throws NoSuchElementException when user does not exist")
        void throwsUsernameNotFoundWhenUserDoesNotExistTest() {
            when(userRepo.findByEmail("unknown")).thenReturn(Optional.empty());

            assertThrows(UsernameNotFoundException.class,
                () -> userService.getUserByEmail("unknown")
            );
        }
    }

}
