spring.application.name=fintrack

spring.datasource.username=test
spring.datasource.password=test

# WARNING: Don't forget to switch the next line to validate before going into production
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false


